services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      target: dev
    restart: unless-stopped
    environment:
      - PORT=${WEB_PORT}
    volumes:
      - .:/srv
      - simple-react-node_modules:/srv/node_modules
    ports:
      - 127.0.0.1:${WEB_PORT}:${WEB_PORT}

volumes:
  simple-react-node_modules:
    external: true
